# Generated by Django 5.0.2 on 2024-04-22 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0003_customuser_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='telegram',
        ),
    ]
