# Generated by Django 5.0.2 on 2024-05-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0004_remove_customuser_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
