# Generated by Django 5.0.2 on 2024-05-01 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0005_customuser_is_vip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_vip',
        ),
    ]
