# Generated by Django 5.0.2 on 2024-04-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0003_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='telegram',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('1', 'created'), ('2', 'confirmed'), ('3', 'rejected'), ('4', 'special')], default='1', max_length=30),
        ),
    ]
